version: '3.8'

services:
  db:
    restart: always
    image: "postgres:15.2-alpine"
    container_name: "sudosumo_db"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}


  backend:
    container_name: "spring_boot_app"
    build:
      context: sudosumo_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target:/workspace/app/target
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      JWK_SET_URI: ${JWK_SET_URI}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_SUCCESS_LOGIN_ROUTE: ${FRONTEND_SUCCESS_LOGIN_ROUTE}
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: docs
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - REACT_APP_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REACT_APP_GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - REACT_APP_GOOGLE_LOGIN_BACKEND_URL=${GOOGLE_LOGIN_BACKEND_URL}

volumes:
  db:
    driver: local
