FROM eclipse-temurin:17-jdk-alpine
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src /workspace/app/src

RUN ./mvnw clean package -DskipTests

ARG JAR_FILE=./target/*.jar
RUN cp ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar ${0} ${@}"]