version: '3.8'
services:
  db:
    restart: always
    image: "postgres:15.2-alpine"
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
        - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 1m
      timeout: 10s
      retries: 2

  backend:
    container_name: "backend"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    volumes:
      - ./target:/workspace/app/target
    networks:
        - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
        - db

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge