spring:
  datasource:
    url: jdbc:postgresql://db:5432/sudosumo_db
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    sql:
      init:
        mode: always
server:
  port: 8080
  servlet:
    context-path: ${APP_SERVER_CONTEXT_PATH:/}