spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/${POSTGRES_DB}}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    sql:
      init:
        mode: always
server:
  port: ${APP_SERVER_PORT:8080}
  servlet:
    context-path: ${APP_SERVER_CONTEXT_PATH:/}