spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    sql:
      init:
        mode: always
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                redirect-uri: ${GOOGLE_REDIRECT_URI}
                scope:
                - email
                - profile
        provider:
            google:
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}


server:
  port: 8080
  servlet:
    context-path: ${APP_SERVER_CONTEXT_PATH:/}