version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - REACT_APP_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REACT_APP_GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - REACT_APP_GOOGLE_LOGIN_BACKEND_URL=${GOOGLE_LOGIN_BACKEND_URL}